projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: ${env:PRISMA_ENDPOINT}

  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
